// Code generated by protoc-gen-go.
// source: command.proto
// DO NOT EDIT!

/*
Package commandproto is a generated protocol buffer package.

It is generated from these files:
	command.proto

It has these top-level messages:
	Event
	Payload
	Command
	DeviceInformation
	InstallProfile
*/
package commandproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	Id      string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Time    int64    `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Payload *Payload `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Event) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Payload struct {
	CommandUuid string   `protobuf:"bytes,1,opt,name=command_uuid,json=commandUuid" json:"command_uuid,omitempty"`
	Command     *Command `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Payload) GetCommandUuid() string {
	if m != nil {
		return m.CommandUuid
	}
	return ""
}

func (m *Payload) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

type Command struct {
	RequestType       string             `protobuf:"bytes,1,opt,name=request_type,json=requestType" json:"request_type,omitempty"`
	DeviceInformation *DeviceInformation `protobuf:"bytes,2,opt,name=device_information,json=deviceInformation" json:"device_information,omitempty"`
	InstallProfile    *InstallProfile    `protobuf:"bytes,3,opt,name=install_profile,json=installProfile" json:"install_profile,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Command) GetRequestType() string {
	if m != nil {
		return m.RequestType
	}
	return ""
}

func (m *Command) GetDeviceInformation() *DeviceInformation {
	if m != nil {
		return m.DeviceInformation
	}
	return nil
}

func (m *Command) GetInstallProfile() *InstallProfile {
	if m != nil {
		return m.InstallProfile
	}
	return nil
}

type DeviceInformation struct {
	Queries []string `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
}

func (m *DeviceInformation) Reset()                    { *m = DeviceInformation{} }
func (m *DeviceInformation) String() string            { return proto.CompactTextString(m) }
func (*DeviceInformation) ProtoMessage()               {}
func (*DeviceInformation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeviceInformation) GetQueries() []string {
	if m != nil {
		return m.Queries
	}
	return nil
}

type InstallProfile struct {
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *InstallProfile) Reset()                    { *m = InstallProfile{} }
func (m *InstallProfile) String() string            { return proto.CompactTextString(m) }
func (*InstallProfile) ProtoMessage()               {}
func (*InstallProfile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *InstallProfile) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "commandproto.Event")
	proto.RegisterType((*Payload)(nil), "commandproto.Payload")
	proto.RegisterType((*Command)(nil), "commandproto.Command")
	proto.RegisterType((*DeviceInformation)(nil), "commandproto.DeviceInformation")
	proto.RegisterType((*InstallProfile)(nil), "commandproto.InstallProfile")
}

func init() { proto.RegisterFile("command.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x91, 0xd1, 0x4a, 0xb4, 0x40,
	0x18, 0x86, 0x19, 0xfd, 0xff, 0x64, 0xbf, 0xdd, 0x8c, 0x1d, 0x08, 0x3c, 0x08, 0x32, 0x8f, 0x24,
	0xc8, 0xa0, 0x2e, 0xa1, 0xf6, 0x60, 0x4f, 0x62, 0x19, 0xea, 0xac, 0x10, 0xdb, 0xf9, 0x16, 0x3e,
	0x50, 0xc7, 0xd5, 0x71, 0xc1, 0xeb, 0xeb, 0xc6, 0x42, 0x9d, 0xd9, 0xb2, 0x3d, 0xf3, 0x7d, 0x7d,
	0x78, 0x5e, 0x9d, 0x81, 0xf3, 0xad, 0x2a, 0x8a, 0xac, 0x94, 0x49, 0x55, 0x2b, 0xad, 0xf8, 0xc2,
	0xc4, 0x21, 0x45, 0xef, 0xf0, 0x7f, 0x75, 0xc0, 0x52, 0x73, 0x1f, 0x1c, 0x92, 0x01, 0x0b, 0x59,
	0x3c, 0x13, 0x0e, 0x49, 0xce, 0xe1, 0x9f, 0xa6, 0x02, 0x03, 0x27, 0x64, 0xb1, 0x2b, 0x86, 0x67,
	0x7e, 0x0f, 0x5e, 0x95, 0x75, 0xb9, 0xca, 0x64, 0xe0, 0x86, 0x2c, 0x9e, 0x3f, 0x5c, 0x26, 0xbf,
	0x65, 0xc9, 0x66, 0x7c, 0x29, 0x2c, 0x15, 0x7d, 0x80, 0x67, 0x3a, 0x7e, 0x03, 0x76, 0x38, 0x6d,
	0xdb, 0xe3, 0xd2, 0xdc, 0x74, 0x6f, 0x2d, 0xc9, 0x5e, 0x6f, 0xe2, 0xb0, 0x7a, 0xa2, 0x7f, 0x1a,
	0x83, 0xb0, 0x54, 0xf4, 0xc5, 0xc0, 0x33, 0x65, 0xef, 0xaf, 0x71, 0xdf, 0x62, 0xa3, 0x53, 0xdd,
	0x55, 0x68, 0xfd, 0xa6, 0x7b, 0xed, 0x2a, 0xe4, 0x2f, 0xc0, 0x25, 0x1e, 0x68, 0x8b, 0x29, 0x95,
	0x3b, 0x55, 0x17, 0x99, 0x26, 0x55, 0x9a, 0xa9, 0xeb, 0xe9, 0xd4, 0xf3, 0xc0, 0xad, 0x7f, 0x30,
	0xb1, 0x94, 0x7f, 0x2b, 0xbe, 0x82, 0x0b, 0x2a, 0x1b, 0x9d, 0xe5, 0x79, 0x5a, 0xd5, 0x6a, 0x47,
	0x39, 0x9a, 0x63, 0xb9, 0x9a, 0xca, 0xd6, 0x23, 0xb4, 0x19, 0x19, 0xe1, 0xd3, 0x24, 0x47, 0x77,
	0xb0, 0x3c, 0x99, 0xe3, 0x01, 0x78, 0xfb, 0x16, 0x6b, 0xc2, 0x26, 0x60, 0xa1, 0x1b, 0xcf, 0x84,
	0x8d, 0xd1, 0x2d, 0xf8, 0x53, 0x61, 0xcf, 0xda, 0x6b, 0xe9, 0xff, 0x7a, 0x71, 0x3c, 0xff, 0xcf,
	0xb3, 0xe1, 0x03, 0x1e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x08, 0xd9, 0xa1, 0xac, 0x03, 0x02,
	0x00, 0x00,
}
